### PR TITLE
Table7

### PR DESCRIPTION
**Pull request by RocketUzarraga**
adding table stuff i am very sorry

### CODE REVIEW

**Comment by RocketUzarraga** [comment]
i aint gonna lie i might have accidentally removed something important while trying to update

**Comment by AyushGarg4** [comment]
> i aint gonna lie i might have accidentally removed something important while trying to update

@RocketUzarraga Is this completed/do you want me to merge yet, or are you still working on this?

**Comment by RocketUzarraga** [comment]
it's completed, yeah

**Review by FranklinLiu-DUSD — APPROVED** [review]
gaming

**Pull request merged**
