### PR TITLE
Added Irene's Seating Chart :)

### PR DESCRIPTION
**Pull request by PatrickIreneFaustina**
yippee! :)

### CODE REVIEW

**Review by FranklinLiu-DUSD — APPROVED** [review]
looks good

**Comment by FranklinLiu-DUSD** [comment]
@PatrickIreneFaustina pls add your audio file and image and open a new pull request. sorry for the inconvenience

**Comment by PatrickIreneFaustina** [comment]
> @PatrickIreneFaustina pls add your audio file and image and open a new pull request. sorry for the inconvenience

franklin do i need to finish this?

**Comment by PatrickIreneFaustina** [comment]
> @PatrickIreneFaustina pls add your audio file and image and open a new pull request. sorry for the inconvenience

is there something i need to fix?

**Comment by FranklinLiu-DUSD** [comment]
> > @PatrickIreneFaustina pls add your audio file and image and open a new pull request. sorry for the inconvenience
> 
> is there something i need to fix?

sorry for the late reply, i just saw the changes on your branch. its pretty late now so i'll just make the pull request for you

**Pull request merged**
